# docker 컨테이너 버전을 명시
version: '3'
# services는 컨테이너
services:
  nextjs:
    build:
      context: .
      dockerfile: ./docker/next.Dockerfile
    ports:
      - 3000:3000

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/nginx.Dockerfile
    ports:
      - 80:80
    depends_on:
      - nextjs
