// Vanilla Extract 로더 추가
// webpack.config.js
const { VanillaExtractPlugin } = require('@vanilla-extract/webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
module.exports = {
  plugins: [new VanillaExtractPlugin(), new MiniCssExtractPlugin()],
  module: {
    rules: [
      {
        test: /\.css\.ts$/, // Targets only CSS files generated by vanilla-extract
        use: [
          'style-loader',
          'css-loader',
          '@vanilla-extract/webpack-plugin/loader',
        ],
      },
    ],
  },
};
