name: 'Continuous Integration'

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quality:
    name: 'CI: Check quality'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: yarn Build
        run: yarn build

      - name: Check typescript
        run: yarn type:check

      - name: Check prettier
        run: yarn prettier

      - name: Check eslint
        run: yarn lint
